{% set version = "0.5.1" %}
{% set soversion = ".".join(version.split(".")[:3]) %}
{% set somajor = version.split(".")[0] %}
{% set arm_variant_type = arm_variant_type|default("sbsa") %}

package:
  name: libnvpl-rand-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/nvpl/redist/nvpl_rand/linux-sbsa/nvpl_rand-linux-sbsa-{{ version }}-archive.tar.xz
  sha256: 4a75b8256d46d22fc00f4ef3bb8d0d7c5055034e587cb04bd56365a396bc281b

build:
  number: 1
  # nvpl is only for ARM architecture
  skip: true  # [not aarch64]
  script:
    - cp -rv include $PREFIX
    - cp -rv lib $PREFIX
    - check-glibc "$PREFIX"/lib*/*.so.* "$PREFIX"/bin/* "$PREFIX"/targets/*/lib*/*.so.* "$PREFIX"/targets/*/bin/*  # [linux]

requirements:
  build:
    - cf-nvidia-tools 1.*  # [linux]

outputs:

  - name: libnvpl-rand-dev
    build:
      run_exports:
        - {{ pin_subpackage("libnvpl-rand" ~ somajor ) }}
    files:
      - include/nvpl_rand*
      - include/nvpl_rand*/**
      - lib/cmake/nvpl_rand*/**
      - lib/libnvpl_rand*.so
    requirements:
      host:
        - {{ pin_subpackage("libnvpl-rand" ~ somajor, exact=True) }}
        - _nvpl_dev_mutex
        - libnvpl-common-dev
      run:
        - _nvpl_dev_mutex
        - {{ pin_compatible("libnvpl-common-dev", exact=True) }}
        - {{ pin_subpackage("libnvpl-rand" ~ somajor, exact=True) }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}
    test:
      files:
        - test
      requires:   # [build_platform == target_platform]
        - {{ compiler("c") }}  # [build_platform == target_platform]
        - {{ compiler("cxx") }}  # [build_platform == target_platform]
        - {{ stdlib("c") }}  # [build_platform == target_platform]
        - cmake   # [build_platform == target_platform]
        - ninja  # [build_platform == target_platform]
      commands:
        - cmake ${CMAKE_ARGS} -GNinja test  # [build_platform == target_platform]
        - cmake --build .  # [build_platform == target_platform]
        - test -f $PREFIX/include/nvpl_rand.h
        - test -f $PREFIX/lib/cmake/nvpl_rand/nvpl_rand-config.cmake
        - test -f $PREFIX/lib/libnvpl_rand.so
        - test -f $PREFIX/lib/libnvpl_rand_mt.so

  - name: libnvpl-rand{{ somajor }}
    build:
      run_exports:
        - {{ pin_subpackage("libnvpl-rand" ~ somajor ) }}
    files:
      - lib/libnvpl_rand*.so.*
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ stdlib("c") }}
        - arm-variant * {{ arm_variant_type }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}
    test:
      commands:
        - test -f $PREFIX/lib/libnvpl_rand.so.{{ somajor }}
        - test -f $PREFIX/lib/libnvpl_rand.so.{{ soversion }}
        - test -f $PREFIX/lib/libnvpl_rand_mt.so.{{ somajor }}
        - test -f $PREFIX/lib/libnvpl_rand_mt.so.{{ soversion }}

about:
  home: https://developer.nvidia.com/nvpl
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_file: LICENSE
  license_url: https://docs.nvidia.com/nvpl/license.html
  summary: >-
    The NVIDIA Performance Libraries (NVPL) are a collection of high performance mathematical libraries optimized for the NVIDIA Grace Armv9.0 architecture.
  description: >-
    The NVIDIA Performance Libraries (NVPL) are a collection of high performance mathematical libraries optimized for the NVIDIA Grace Armv9.0 architecture.

    These CPU-only libraries have no dependencies on CUDA or CTK, and are drop in replacements for standard C and Fortran mathematical APIs allowing HPC applications to achieve maximum performance on the Grace platform.
  doc_url: https://docs.nvidia.com/nvpl/

extra:
  feedstock-name: libnvpl-rand
  recipe-maintainers:
    - conda-forge/cuda
